#!/bin/lua

local length = require("utils").length

local function print_help()
	print("Usage: find < what > < where >")
end

local function main()

	if length(arg) ~= 2 then
		print_help()
	else
		local what = arg[1]
		local where = arg[2]
		local to_exec = string.format("grep --recursive --line-number --color=always '%s' '%s'" , what, where)
		os.execute(to_exec)
		-- print(to_exec)
	end
end

main()
