#!/bin/lua

local length = require("utils").length

local function print_help()
	print("Usage: gitup < message >")
end

local function main()

	if length(arg) ~= 1 then
		print_help()
	else
		local message = arg[1]

		os.execute("git add .")
		os.execute(string.format("git commit -m '%s'", message))
		os.execute("git push")
	end
end

main()
