#!/bin/lua

require("utils").using("utils")
local lfs = require("lfs")

local function get_content(directory)
	local files = {hidden={}, visible={}}
	local dirs = {hidden={}, visible={}}

	local dir, err = pcall(lfs.dir, directory)
    if not dir then
        return nil
    end

    for entry in lfs.dir(directory) do
        if entry ~= "." and entry ~= ".." then
			local path = directory .. "/" .. entry
            local mode = lfs.attributes(path, "mode")
            if mode == "file" then
            	if slice(entry, 1, 1) == "." then
	            	table.insert(files.hidden, entry)
            	else
	            	table.insert(files.visible, entry)
            	end
            else
            	if slice(entry, 1, 1) == "." then
            		table.insert(dirs.hidden, entry)
            	else
            		table.insert(dirs.visible, entry)
            	end
            end
        end
    end

    local content = {files = files, dirs = dirs}
    sorted_content = deep_sort(content)
    return sorted_content
end

local function main()
	-- ANSI escape codes for colors
    local colors = {
        default = "\27[0m",
        blue = "\27[01;34m",
        red = "\27[01;31m"
    }

	local path = arg[1] or "."
    local mode = lfs.attributes(path, "mode")

    if not mode then
        print(colors.red .. "Error: cannot access " .. path .. ": No such file or directory" .. colors.default)
    elseif mode == "file" then
        print(colors.default .. path .. colors.default)
    else
        local content = get_content(path)
        if not content then
            print(colors.red .. "Error: could not read content of " .. directory .. colors.default)
        else

        	-- print hidden directories
			for _, dir in pairs(content["dirs"]["hidden"]) do
	        	print(colors.blue .. dir .. colors.default)
	        end

	        -- print visible directories
	        for _, dir in pairs(content["dirs"]["visible"]) do
	            print(colors.blue .. dir .. colors.default)
	        end

			-- print hidden files
			for _, file in pairs(content["files"]["hidden"]) do
	        	print(colors.default .. file .. colors.default)
	        end

	        -- print visible files
	        for _, file in pairs(content["files"]["visible"]) do
	            print(colors.default .. file .. colors.default)
	        end
	        
        end
    end
end

main()

